style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120

naming:
  FunctionNaming:
    active: true
    functionPattern: '^[a-z][A-Za-z0-9]*$'
